# DO NOT EDIT THIS FILE!
#
# Python module JARA_ARM__POA generated by omniidl

import omniORB
omniORB.updateModule("JARA_ARM__POA")

# ** 1. Stub files contributing to this module
import ManipulatorCommonInterface_Middle_idl
import ManipulatorCommonInterface_Common_idl

# ** 2. Sub-modules

# ** 3. End
